sudo: required

dist: trusty

language: generic

env:
  global:
    - ROS_WS=~/ros_ws
    - LWR_WS=$ROS_WS/lwr_ws
    - LWR_CONTROLLERS_WS=$ROS_WS/lwr_controllers_ws
    - EXT_WS=$ROS_WS/ext_ws
    - ROS_DISTRO=indigo
  
script:
  - bash lwr_setup.bash
